name: Build Android APK (Internal)

on:
  push:
    branches:
      - main  # troque se sua branch for outra

  workflow_dispatch:  # permite rodar manualmente

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - run: dotnet workload install maui

      - run: dotnet restore

      - run: dotnet publish src/PasswordManager.App/PasswordManager.App.csproj -f net10.0-android -c Release -o publish

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: publish/**/*.apk
